# Generated by Django 3.2 on 2021-05-02 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('email', models.CharField(max_length=1000)),
                ('phone', models.IntegerField()),
                ('desc', models.CharField(max_length=10000)),
                ('dated_created', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=1000)),
                ('product_name', models.CharField(max_length=10000)),
                ('qty', models.IntegerField()),
                ('to', models.CharField(max_length=1000)),
                ('tracking_no', models.IntegerField()),
                ('product_id', models.IntegerField()),
                ('date_updated', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10000)),
                ('desc', models.CharField(max_length=10000)),
                ('img_path', models.CharField(max_length=10000)),
                ('price', models.IntegerField()),
                ('date_updated', models.DateField()),
                ('user_id', models.IntegerField()),
                ('stock', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Stock_inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=10000)),
                ('product_id', models.IntegerField()),
                ('desc', models.CharField(max_length=10000)),
                ('qty', models.IntegerField()),
                ('date_updated', models.DateField()),
            ],
        ),
    ]
