# Generated by Django 3.2.2 on 2021-05-07 17:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20210507_1731'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='img_path',
            new_name='image',
        ),
        migrations.AlterField(
            model_name='contact',
            name='dated_created',
            field=models.DateField(default=datetime.datetime(2021, 5, 7, 17, 34, 5, 244131)),
        ),
    ]
