# Generated by Django 3.2.2 on 2021-05-08 07:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_auto_20210508_0709'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='desc',
            new_name='Use_Instruction',
        ),
        migrations.AddField(
            model_name='product',
            name='uses',
            field=models.CharField(default=0, max_length=10000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contact',
            name='dated_created',
            field=models.DateField(default=datetime.datetime(2021, 5, 8, 7, 13, 42, 510578)),
        ),
    ]
