# Generated by Django 3.2.2 on 2021-05-08 07:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_auto_20210508_0713'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Volume',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contact',
            name='dated_created',
            field=models.DateField(default=datetime.datetime(2021, 5, 8, 7, 29, 29, 344197)),
        ),
    ]
