# Generated by Django 3.2.2 on 2021-05-13 15:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_auto_20210513_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='dated_created',
            field=models.DateField(default=datetime.datetime(2021, 5, 13, 15, 32, 56, 218378)),
        ),
        migrations.AlterField(
            model_name='orderupdate',
            name='tracking_no',
            field=models.CharField(default='', max_length=1000, null=True),
        ),
    ]
