# Generated by Django 3.2.2 on 2021-05-13 15:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_auto_20210513_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='dated_created',
            field=models.DateField(default=datetime.datetime(2021, 5, 13, 15, 34, 18, 747085)),
        ),
        migrations.AlterField(
            model_name='orderupdate',
            name='tracking_no',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
    ]
