# Generated by Django 3.2.2 on 2021-05-17 13:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_auto_20210515_1624'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Stock_inventory',
        ),
        migrations.RemoveField(
            model_name='orderupdate',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='orderupdate',
            name='date_updated',
            field=models.DateField(default=datetime.datetime(2021, 5, 17, 13, 7, 26, 624820)),
        ),
        migrations.AlterField(
            model_name='contact',
            name='dated_created',
            field=models.DateField(default=datetime.datetime(2021, 5, 17, 13, 7, 26, 625270)),
        ),
    ]
